{
    "identifiers": [
        "logging",
        "time",
        "typing",
        "Any",
        "requests",
        "url",
        "logger",
        "logging",
        "Logger",
        "retries",
        "backoff_in_seconds",
        "timeout",
        "DEFAULT_TIMEOUT",
        "kwargs",
        "Any",
        "requests",
        "Response",
        "logger",
        "debug",
        "url",
        "attempt",
        "retries",
        "last_exception",
        "time",
        "sleep",
        "backoff_in_seconds",
        "requests",
        "get",
        "url",
        "timeout",
        "timeout",
        "kwargs",
        "response",
        "raise_for_status",
        "response",
        "requests",
        "exceptions",
        "HTTPError",
        "e",
        "e",
        "attempt",
        "retries",
        "backoff_in_seconds",
        "logger",
        "warning",
        "attempt",
        "retries",
        "will_retry",
        "e",
        "e",
        "e",
        "attempt",
        "retries",
        "backoff_in_seconds",
        "logger",
        "warning",
        "attempt",
        "retries",
        "will_retry",
        "url",
        "e",
        "last_exception",
        "logger",
        "error",
        "url",
        "last_exception",
        "last_exception"
    ],
    "literals": [
        "f\"http GET {url}\"",
        "\"\"",
        "f\" (will retry in {backoff_in_seconds} seconds) \"",
        "f\"attempt {attempt + 1} of {retries} failed:{will_retry}{e}\"",
        "\"\"",
        "f\" (will retry in {backoff_in_seconds} seconds) \"",
        "f\"attempt {attempt + 1} of {retries}{will_retry}: unexpected exception during GET {url}: {e}\"",
        "f\"last retry of GET {url} failed with {last_exception}\"",
        "\"unreachable\""
    ],
    "variables": [
        "DEFAULT_TIMEOUT",
        "last_exception",
        "response",
        "last_exception",
        "will_retry",
        "will_retry",
        "last_exception",
        "will_retry",
        "will_retry"
    ],
    "comments": [
        "HTTPError includes the attempted request, so don't include it redundantly here",
        "this is an unexpected exception type, so include the attempted request in case the",
        "message from the unexpected exception doesn't."
    ],
    "docstrings": [],
    "functions": [
        "get"
    ],
    "classes": []
}