{
    "identifiers": [
        "sys",
        "error",
        "error_detail",
        "sys",
        "error_detail",
        "exc_info",
        "exc_tb",
        "tb_frame",
        "f_code",
        "co_filename",
        "format",
        "file_name",
        "exc_tb",
        "tb_lineno",
        "error",
        "error_message",
        "error_message",
        "error_detail",
        "sys",
        "error_message",
        "error_message_detail",
        "error_message",
        "error_detail",
        "error_detail",
        "error_message"
    ],
    "literals": [
        "\"Error occured in python script name [{0}] line number [{1}] error message[{2}]\""
    ],
    "variables": [
        "_",
        "_",
        "exc_tb",
        "file_name",
        "error_message",
        "error_message"
    ],
    "comments": [],
    "docstrings": [],
    "functions": [
        "error_message_detail",
        "__int__",
        "__str__"
    ],
    "classes": [
        "CustomException"
    ]
}